FROM debian:trixie

RUN apt-get update
RUN apt-get install -y unzip curl jq

RUN export VER=$(curl -H "Accept: application/vnd.github+json" https://api.github.com/repos/bitwarden/clients/releases | jq  -r 'sort_by(.published_at) | reverse | .[].name | select( index("CLI") )' | sed 's:.*CLI v::' | head -n 1) && \
  curl -LO "https://github.com/bitwarden/clients/releases/download/cli-v{$VER}/bw-linux-{$VER}.zip" \
  && unzip *.zip && chmod +x ./bw

RUN echo "./bw config server https://vault.datasektionen.se" >> run.sh
RUN echo "./bw login --apikey" >> run.sh
RUN echo "./bw serve --hostname all" >> run.sh
RUN chmod +x run.sh


ENTRYPOINT [ "bash", "./run.sh" ]
